AWSTemplateFormatVersion: 2010-09-09
Description: Creating RDS using CFT

Parameters:
  DBName:
    Default: EmployeeT
    Description: My Database Table Name
    Type: String

  DBInstanceIdentifier:
    Default: mydatabase-rds
    Description: My Database Name
    Type: String

  AllocatedStorage:
    Default: 20
    Description: Storage in GiB
    Type: Number

Resources:
  MyDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: !Ref DBName # Database Table Name
      DBInstanceIdentifier: !Ref DBInstanceIdentifier # Database Name
      AllocatedStorage: !Ref AllocatedStorage
      Engine: MySQL
      EngineVersion: "8.4.9"
      DBInstanceClass: db.t4g.micro
      MasterUsername: admin
      MasterUserPassword: Admin123
      MultiAZ: false
