AWSTemplateFormatVersion: 2010-09-09
Description: Creating and EC2 Instance using CloudFormation
# -------------------- Parameter Section -----------------------------
# Parameters:

# Mappings
Mappings:
  UbuntuAMIs:
    us-east-1:
      ubuntu2604: ami-0b6d9d3d33ba97d99
      ubuntu2404: ami-0f8a61b66d1accaee
    us-west-1:
      ubuntu2604: ami-02167eae61967e403
      ubuntu2404: ami-096f5760b00bcd95c

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      # AvailabilityZone: us-east-1a
      ImageId: !FindInMap
        - UbuntuAMIs
        - !Ref AWS::Region # This sets the current region when we upload the template in CloudFormation
        - ubuntu2404
      InstanceType: t3.micro
      KeyName: awsKey2
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: "0"
          SubnetId: !Ref mysubnet
          GroupSet:
            - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: Instance-1
      # UserData Section to install startup scripts
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update -y
          sudo apt install -y apache2
          sudo systemctl start apache2
          sudo systemctl enable apache2

  # Create a VPC
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 11.0.0.0/16
      InstanceTenancy: default
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: vpc-cft

  # Security Group with ingress rules 22 and 80
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ec2-sg
      GroupDescription: This is for port 22 and 80
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: ec2-sg

  # Create Internet Gateway
  MyIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: my-igw

  # Attach Internet Gateway to VPC
  myInternetGatewayVPCattachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref myVPC
      InternetGatewayId: !Ref MyIGW

  # Create a Subnet
  mysubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: us-east-1a
      VpcId: !Ref myVPC
      CidrBlock: 11.0.1.0/24
      Tags:
        - Key: Name
          Value: my-subnet

  # Create Route Table
  Myrt:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref myVPC
      Tags:
        - Key: Name
          Value: my-rt

  # Associate Route table with subnet
  subnetAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref mysubnet
      RouteTableId: !Ref Myrt

  # Associate IGW to Route Table
  InternetGatewayAssociation:
    Type: AWS::EC2::Route
    DependsOn: myInternetGatewayVPCattachment # Waits until IGW attached to the VPC
    Properties:
      GatewayId: !Ref MyIGW
      RouteTableId: !Ref Myrt
      DestinationCidrBlock: 0.0.0.0/0

#  To display in the outputs section of our stack
Outputs:
  Apacheurl:
    Description: To display the web url of apache2
    # Value: !Sub "http://{MyInstance.PublicIp}"
    Value: !Join ["://", [http, !GetAtt MyInstance.PublicIp]]
