AWSTemplateFormatVersion: 2010-09-09
Description: Creating VPC using CFT

Parameters:
  myVpcCIDR:
    Description: Custom CIDR
    Type: String
    Default: 10.0.0.0/16

  # Menu for selecting AZ's
  TargetAZForweb1:
    Description: Select an AZ from the menu
    Type: AWS::EC2::AvailabilityZone::Name

  TargetAZFordb1:
    Description: Select an AZ from the menu
    Type: AWS::EC2::AvailabilityZone::Name

  web1cidr:
    Description: Subnets CIDR
    Type: String
    Default: 10.0.1.0/24

  web2cidr:
    Description: Subnets CIDR
    Type: String
    Default: 10.0.2.0/24

  database1cidr:
    Description: Subnets CIDR
    Type: String
    Default: 10.0.3.0/24

  database2cidr:
    Description: Subnets CIDR
    Type: String
    Default: 10.0.4.0/24

Resources:
  VpcUsingCFT: # logical ID for VPC
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref myVpcCIDR
      InstanceTenancy: default
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: ntier-vpc
        - Key: Env
          Value: Dev

  # Create subnets

  web1subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcUsingCFT
      CidrBlock: !Ref web1cidr
      AvailabilityZone: !Ref TargetAZForweb1
      Tags:
        - Key: Name
          Value: webserver-1

  web2subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcUsingCFT
      CidrBlock: !Ref web2cidr
      Tags:
        - Key: Name
          Value: webserver-2

  db1subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcUsingCFT
      CidrBlock: !Ref database1cidr
      AvailabilityZone: !Ref TargetAZFordb1
      Tags:
        - Key: Name
          Value: Database-Server-1

  db2subnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VpcUsingCFT
      CidrBlock: !Ref database2cidr
      Tags:
        - Key: Name
          Value: Database-Server-2
